language: python
dist: xenial

services:
  - postgresql

# Cache the pip files
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.nvm
    - node_modules
    - wger/node_modules

# Use container infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# Python versions to test
python:
  - "3.6"
  - "3.7"

# Manually define here the combinations environment variables to test
# https://github.com/travis-ci/travis-ci/issues/1519
env:
  - TEST_MOBILE=True  DB=postgresql TRAVIS_NODE_VERSION="6"
  - TEST_MOBILE=True  DB=sqlite     TRAVIS_NODE_VERSION="6"
  - TEST_MOBILE=False DB=postgresql TRAVIS_NODE_VERSION="6"
  - TEST_MOBILE=False DB=sqlite     TRAVIS_NODE_VERSION="6"

# Install the application
install:
  # Install requirements
  - pip install -r requirements_devel.txt
  - pip install -r requirements_forked.txt
  - python setup.py develop
  - npm install -g gulp gulp-cli
  - npm install
  - cd wger
  - if [[ "$DB" = "postgresql" ]]; then pip install psycopg2; fi

  # Setup application
  - if [[ "$DB" = "sqlite" ]]; then wger create_settings; fi
  - if [[ "$DB" = "postgresql" ]]; then wger create_settings --database-type postgresql; fi

  # change back to the source folder
  - cd ..

# Create test databases
before_script:
  - if [[ "$DB" = "postgresql" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;' -U postgres; fi
  - if [[ "$DB" = "postgresql" ]]; then psql -c 'CREATE DATABASE test_wger;' -U postgres; fi

# Do the tests
script:
  # Python and Javascript linting
  - gulp lint

  # Regular application
  - coverage run --source='.' ./manage.py test --parallel

  # Code coverage
  - coverage report
